a.txt

[BE송예린] step-1 git test 

---

src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

##구현 내용
1. request를 BufferedReader를 통해 line 별로 읽어들여 logger.debug를 하고, url만 parsing을 하여 file을 보낸다.
2. thread 대신 concurrent 라이브러리를 사용한다. executorService를 사용하여 socket으로 들어온 connection들을  RequestHandler 객체 생성인자로 넣는다.
##고민 사항
was 구조에 대해 공부해볼 필요가 있어보인다.

[zensen6] step-1 index.html 응답

---

README.md
src/main/java/dto/RequestDto.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

구현 내용
index.html 렌더링 하기
url로 넘어온 값에서 /index.html을 추출하고 확장자가 .html이면 resources/templates에서, 그 외에는 resources/static에서 찾아 body에 담게 하였습니다.
request 내용 출력하기
request에 담긴 내용중 현재 mission에 필요한 내용을 정리해서 requestDto에 담고 logger.debug를 사용하여 출력하였습니다.
java의 thread 대신 concurrent를 사용하여 connection을 처리하도록 변경하였습니다.
고민 사항
thread 와 concurrent의 차이가 무엇인지 이해하기위해 노력했습니다.
기타

feat : add requestHandler 

---

src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

- BufferReader를 활용한 HTTP Request 요청 출력
- index.html 파일 응답
- 기존 자바 thread >> concurrent 패키지 사용으로 수정
제대로 구현 한 건지 모르겠다..
OOP와 클린코딩을 어떻게 적용하면 좋을지 고민이다
자바 Thread 공부하기

[ossu] step-1 index.html 응답

---

src/main/java/util/ResourceLoader.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/main/resources/logback.xml

1. WebServer - Thread 기반에서 ExecutorService 기반으로 변경
2. RequestHandler - templates 경로에서 파일을 읽어 response하도록 변경
- /css/, /fonts/, /images/, /js/ 로 시작하는 경로는 static 경로에서 읽어오도록 별도 처리
- static resource에서 불러올 경우, 확장자에 따라 content-type을 다르게 반환하도록 처리 (ResourceLoader)
분명 response에서 제대로된 css 파일을 돌려주는데, 왜 html에서는 css 적용이 되지 않는가...
-> content-type을 text/html로 고정해서 보내줬기 때문이다. 파일 종류에 따라 다르게 보내줄 필요가 있었음
나름 클린코딩을 한 것 같아서 뿌듯

[insiderhj] step-1 index.html 응답

---

src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. concurrent 패키지 속 Executors를 사용하여 스레드 풀을 미리 생성하고 요청을 받을때마다 스레드를 하나씩 할당 하는 기능
2. Header Request의 정보를 Logger를 통해 기록을 남기는 기능
3. Header Request 속 path 정보를 불러와 매칭되는 html 파일을 body에 Return 하는 기능
터미널을 통해 Http 요청을 보냈을 때와 브라우저를 통한 Http 요청에따라 헤더의 종류가 달라진다는 점 -> 특히 브라우저를 통한 요청을 할 시 아무런 정보가 없는 connection들이 생성되는 것을 발견하고 Optional을 통해 헤더 정보가 있을때와 없을때를 구분하였으나 OOP와 클린코딩의 관점으로 옳바른 코드를 작성했는지 의문이 든다.
```
String header;
while ((header = bufferedReader.readLine()) != null) {
// ...
}
```
과 같은 코드를 실행하였을때 while문을 벗어나지 못하는데 아직 해결점을 찾지 못했다.

[dlwnsgus07] step-1 index.html 응답

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/model/MimeType.java
src/main/java/model/Request.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

- Thread Pool 의 max 수 제한 
- request 가 null인 경우 처리 방안
- request 관리 
- 확장자에 따라 contentType과 path가 별도로 관리되어야 함
- MineType, Request 객체를 통해 관리하도록 구현

[ddrongy] step-1 index.html 응답

---

src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

* 요청경로인 path를 받아서 Header의 첫 부분을 파싱하여 요청한 경로에 해당하는 html 파일을 보여줍니다.
* html뿐만아니라 html이외의 파일인 js와 css는 static 폴더를 통해 가져오도록 합니다.
* 헤더를 debug의 {}를 이용하여 의미 분석시 더 명확하게 눈에 들어오도록 합니다.
* CachedThreadPool을 이용하여 요청한 만큼의 스레드를 생성하고 사용하지 않는 스레드는 종료시키도록 합니다.
* 스레드에서 lock부분을 어디에 걸어야 할지 아직은 더 고민중입니다.

[Win-9] step-1 index.html 응답

---

src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. index.html 경로로 http get request 시 정적 파일 반환
2. Http request line과 header 로그로 출력
3. concurrent 패키지를 사용한 java thread 코드 리팩토링
Http request line에서 request url이 index.html이면 정적 파일을 반환하고 다른 경우는 일반 string만 return하게 if문으로 일단 구현해놓았는데 모든 url에 대해 이런 식으로 parsing할 수는 없으니 다른 방법이 필요할 것 같음.
concurrent 패키지의 ExecutorService와 Executors를 사용해서 threadpool 기반의 was로 리팩토링. 
threadpool을 사용하여 서버에 다수 요청이 발생할 시 과도한 thread 생성으로 인한 서버 다운 방지가 가능할 것으로 예상되며 클라이언트의 요청마다 쓰레드를 새로 생성할 필요가 없어짐.

[jsLeen] step-1 index.html 응답 구현

---

README.md
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. BufferedReader를 이용하여 HTTP Request를 읽고 파싱
2. HTTP Method, Request Target, Host, Accept 출력
3. Request Target에 담긴 파일 종류에 따라 경로 설정
- .html: ./src/main/resources/templates
- 그 외: ./src/main/resources/static
4. Http Request에서 추출한 Accept를 이용하여 Response 속 Content-Type 설정
5. Thread 기반 구현 -> ExecutorService 인터페이스를 활용 : Thread Pool (고정 크기 5)을 이용한 병렬 처리 구현
1. 파일 종류에 따라 경로와 Response 속 Content-Type이 달라진다는 것을 발견하였다.
어떻게 코드를 짤지 고민하는 과정에서 무엇보다도 HTTP Request 내용을 잘 이해하는 것이 중요하다는 생각이 들었다.
2. 효율적인 메모리 사용을 위해 쓰레드 관리를 어떻게 할 지 고민하였고, 고정된 크기를 이용하여 쓰레드를 재사용하는 쓰레드 풀을 사용하였다.
3. ExecutorService 인터페이스에서 작업 처리를 위해 제공하는 두 메소드 submit()과 execute() 중 어떤 것을 사용할 지 고민하였다.
비동기 테스크의 결과값을 받아볼 수 있고, 스레드 생성 오버헤드가 상대적으로 적은 submit()을 선택하였다.
HTTP Request 헤더를 문자열로 받아 문자열로 파싱하는 방법을 사용하였는데, 더 효율적인 방법이 있나 찾아봐야겠다.

[jbonnie] step-1 index.html 응답 

---

src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. 클라이언트로부터 get 요청이 왔을 때 html 응답
2. http 헤더 중 적절한 값을 로거를 통해 출력
3. concurrent 패키지를 활용해 동시성 구현
1. 작성한 코드가 유지보수에 전혀 좋을 것 같지 않다
2. concurrency가 완벽히 구현됐는지 확신이 없다.
1. 기초부터 다시 배워야 할 것들이 너무 많은 것 같다.

[binaryrain97] step-1 index.html 응답

---

gradle/wrapper/gradle-wrapper.properties
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. 클라이언트가 http://localhost:8080/index.html 로 요청했을 때 index.html을 응답
2. RequestHandler.java에서 로거를 이용하여 헤더에 포함된 내용을 보기 좋게 파싱
3. Concurrent 패키지를 이용하여 스레드풀을 구현하여 처리속도와 안정성 개선, 스레드 개수는 200개로 제한
1. 스레드는 Static으로 선언을하는 것이 맞는지
2. 스레드풀을 구현할 때 KeepAliveTime을 구현하고자 했으나 생각보다 코드가 복잡해져서 더 좋은 방법을 모색중
3. 상수를 최대한 많이 선언하는게 유지보수에 좋은 코드인지
OOP를 생각하며 작성을 했으나 인터페이스를 활용하는 부분이 너무 헷갈린다.

[eyeben] step1 - index.html 응답

---

src/main/java/controller/UserController.java
src/main/java/dto/CreateUserDto.java
src/main/java/model/User.java
src/main/java/util/HttpRequest.java
src/main/java/util/HttpStatus.java
src/main/java/util/ResponseBuilder.java
src/main/java/util/URIParser.java
src/main/java/util/URLMapper.java
src/main/java/webserver/RequestHandler.java
src/test/java/controller/UserControllerTest.java

1. 코드 리팩토링
- util/HttpStatus
- Http Status 코드와 해당하는 메시지들을 짝지어서 enum으로 저장
- util/ResourceLoader
- resources 폴더 아래의 파일들을 불러올 때 사용하는 클래스
- 파일 확장자에 따라서 content-type을 다르게 보내줌
- util/ResponseBuilder
- Http Response를 보낼 때 사용할 클래스. 기존 RequestHandler에서 여기로 옮겼음
- 일반 Response / File / redirect / 404 응답까지 구현완료
- util/URIParser
- URI 주소를 파싱할 때 사용하는 유틸 클래스. 보통 string 처리를 여기서 모아서 하게 됨
- util/URLMapper
- URL과 컨트롤러 함수를 바인딩해주는 클래스.
- 여기에서 바인딩되지 않았을 경우에는 resources 파일에서 찾고, 파일도 없을 경우에는 404 Not found를 돌려주도록 설계해 뒀습니다
2. GET /user/create method 구현
3. /user/create jUnit test 추가
4. HTTP request를 class로 분리하고 필요한 모든 정보를 저장하여 사용할 수 있도록 변경 (로그에는 request method, URI만 출력)
jUnit을 사용하긴 했는데, 이런 방식으로 하는 게 맞나 확실치가 않다 ㅠㅠ

[insiderhj] step-2 GET으로 회원가입

---

src/main/java/dto/Request.java
src/main/java/webserver/RequestHandler.java

1. feeback 이후 기능별로 commit을 분리하여 어떤 수정사항에 대한 pr인지 알수 있게 하였습니다.
2. RequestDto의 접미사를 삭제하였습니다.
```
public class Request {
private String method;
private String url;
}
```
3. 마크다운 문법을 추가하였습니다.
- 현재 step까지는 단순한 작업이라 문제가 없지만 향후 기능이 늘어남에따라 객체지향적이지 않은 설계가 될것으로 예상되어 그에 대한 공부를 하고 있습니다.

[ jomulagy ] step-1 index.html 응답

---

src/main/java/util/RequestParser.java
src/main/java/util/UrlParser.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1) 정적인 html 파일 응답: http://localhost:8080/index.html 로 접속했을 때 src/main/resources/templates 디렉토리의 index.html 파일을 읽어 클라이언트에 응답한다.
2) HTTP Request 내용 출력: 서버로 들어오는 HTTP Request의 내용을 읽고 적절하게 파싱해서 로거(log.debug)를 이용해 출력한다.
> Step
> -  UrlParser 생성
> UrlParser : HTTP 요청 라인에서 URL을 추출하고, 헤더 정보를 필요한 내용만 추출하여 Map 형태로 저장하는 util 클래스
3) 프로젝트 구조 변경: 기존의 프로젝트는 Java Thread 기반으로 작성되어 있다. 이를 Concurrent 패키지를 사용하도록 변경한다.
> Step
> - 수명이 짧은 많은 비동기 작업을 실행하는 것이 주라고 생각하여 CachedThreadPool 사용
> - 공유자원(outputstream)에 대한 동기화 처리
> - excutorservice 종료 조건 중 작업 지속시간 설정
1. FixedThreadPool vs CachedThreadPool
둘 중 어떤 것을 사용해야 하는 것이 더 적합 할지에 대한 고민이 여전히 존재한다.
상황에 따라 알맞은 것을 선택하면 되는 것인데 그 "상황"을 판단하는 것이 어려운 것 같다.
현재는 수명이 짧은 많은 비동기 작업을 실행하는 것이 대부분이라고 생각하여 cachedthreadpool을 선택했는데, fixed를 선택해서 구현하는 경우에도 개수를 몇개로 지정 할지에 대한 고민이 있는 것 같다. …

[yeriinnn] step-1 index.html 응답

---

src/main/java/webserver/HttpRequestInformation.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java

1. http request 내용 출력
2. index.html 화면 띄우기
3. 스레드풀 newCachedThreadPool로 변경
newCachedThreadPool는 스레드가 사용되지 않은지 60초가 되면 자동으로 스레드를 제거해준다고 공부했는데, 스레드 번호가 계속 늘어나서 고민했다. 그래서 현재 실행중인 스레드의 상태와 개수를 출력해봤다. 번호는 계속 늘어나긴하지만, 개수는 3개 정도로 계속 일정한 것을 보니 오래된 스레드는 잘 종료되었고 스레드의 아이디번호만 늘어나는 것이었다.

[eekrwl] step-1 웹 서버 1단계 - index.html 응답

---

build.gradle
src/main/java/controller/GetController.java
src/main/java/controller/PostController.java
src/main/java/util/ControllerMapper.java
src/main/java/util/RequestBuilder.java
src/main/java/util/ResponseBuilder.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/test/java/GetControllerTest.java

“회원가입” 메뉴를 클릭하면 http://localhost:8080/user/form.html 으로 이동, 회원가입 폼을 표시한다. 이 폼을 통해서 회원가입을 할 수 있다.
- HTTP Request에서 회원가입에 필요한 데이터 파싱
- 파싱한 데이터로 User 객체 생성
- 생성한 User 객체를 Database에 저장
서버로 들어오는 HTTP Request의 내용을 읽고 로거(log.debug)를 이용해 출력한다.
- `RequestBuilder` 클래스 생성
- HTTP Request에서 파싱한 데이터들을 통해 RequestBuilder 객체 생성
- 로그 출력 시에는, (중요한 정보라고 생각되는) IP, Port, HTTP Method, URI Path, HTTP Version, Host, Accept 정보만 출력
유지보수가 편한 코드가 되도록 코드품질을 개선해 본다.
- 구현에만 집중하니 한 클래스 내 코드 길이가 너무 길어지고, 또 다양한 내용들이 담겨있어 이를 분리했다.
- Controller
- `GetController`: GET 메소드의 요청을 처리하는 Controller
- `PostController`: POST 메소드의 요청을 처리하는 Controller (아직 POST를 처리해야 할 일은 없었지만 미리 생성해놨다)
- Util
- `ControllerMapper`: 들어온 HTTP Method에 맞는 Controller를 맵핑해주기 위한 Util (희진 님 코드를 참조했다)
- `RequestBuilder`: HTTP Request를 하나의 객체로 관리하기 위해 생성한 클래스
- …

[h-sooah] step-2 GET으로 회원가입

---

README.md
src/main/java/utils/FileReader.java
src/main/java/utils/RequestLogger.java
src/main/java/utils/RequestParser.java
src/main/java/utils/ResponseHandler.java
src/main/java/utils/ResponseSender.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/test/java/RequestParserTest.java

**1. 정적인 html 파일 응답**
RequestHandler에서 RequestParser를 이용해 path 파싱->FileReader 유틸클래스에서 path를 이용하여 Files.readAllBytes를 통해 html 파일 읽어옴.
**2. HTTP Request 내용 출력**
RequestLogger 클래스에서 RequestParser를 통해 헤더를 파싱한 내용을 바탕으로 헤더의 주요 정보를 포함하는 로그 생성
**3. Concurrent Package**
WebServer에서 ExecutorService를 통해 스레드 풀을 생성하고 관리
1. RequestParser의 hashmap을 ConcurrentHashMap을 통해 여러 스레드들이 동시에 hashMap에 접근하는 경우에 대비를 했는데, 효과적인 방법인지 고민된다.
4. RequestHandler클래스의 run 메서드에 있던 파일 읽기, request 로그 남기기, 응답메시지 생성 및 전송을 다 클래스로 분리했는데, 이 클래스들을 어떤 패키지로 묶을 것인지, 적당한 단위로 분리한 것인지 고민되었다.
.

[seojeewon] step-1 index.html 응답

---

README.md
src/main/java/handler/FileHandler.java
src/main/java/handler/RequestHandler.java
src/main/java/handler/UserHandler.java
src/main/java/model/HttpHeader.java
src/main/java/model/HttpRequest.java
src/main/java/model/HttpResponse.java
src/main/java/model/HttpStatusCode.java
src/main/java/utils/HttpStatusCode.java
src/main/java/utils/HttpUtil.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/test/java/utils/HttpUtilTest.java

1. `GET /user/create? ...` 를 통해 User 클래스로 저장할 수 있게 함.
1. GET을 통해 얻은 Query String을 String.split 메소드를 통해 분리하였고, HttpRequest 클래스를 사용해서 Handler가 처리하도록 하였다.
1. HttpUtil에 대한 단위 테스트 코드를 작성하였다.
- RequestHandler의 run이 매우 길어지는 것 같아서 파일 요청에 FileHandler, 유저 클래스 관련 요청에 UserHandler로 분리하여 관리하였다.
- 단위 테스트 작성 범위를 어느 정도로 해야하는 가를 고민하게 되었다.
- 구현에 집중하느라 HTTP, Concurrent, JUnit, OOP, 클린 코딩에 대해 깊이 공부하지 못한 거 같아 다음에는 코딩보단 공부에 더 시간을 할애해야겠다.

[timido7021] step-2 GET으로 회원가입

---

build.gradle
src/main/java/dto/user/request/UserCreateRequestDto.java
src/main/java/handler/DynamicRequestHandler.java
src/main/java/handler/RequestHandler.java
src/main/java/handler/ResponseHandler.java
src/main/java/handler/StaticResourceHandler.java
src/main/java/http/request/HttpRequest.java
src/main/java/http/request/HttpRequestBody.java
src/main/java/http/request/HttpRequestHeader.java
src/main/java/http/request/HttpRequestStartLine.java
src/main/java/http/request/StaticResourceExtension.java
src/main/java/logger/CustomLogger.java
src/main/java/logger/HttpRequestHeader.java
src/main/java/service/Service.java
src/main/java/service/ServiceFactory.java
src/main/java/service/ServiceMapper.java
src/main/java/service/user/OneUserSearchService.java
src/main/java/service/user/TotalUserSearchService.java
src/main/java/service/user/UserCreateService.java
src/main/java/service/user/UserServiceFactory.java
src/main/java/webserver/HttpProcessor.java
src/test/java/service/ServiceMapperTest.java
src/test/java/service/user/UserCreateServiceTest.java

1. 기존 RequestHandler -> HttpProcessor 로 변경
2. WebServer -> HttpProcessor -> dispatcher() -> static / dynamic Handler -> 정적 리소스 반환 / 비지니스 로직 후 반환 구조로 변경
3. HTTP Request 객체화
4. step 2 User 회원가입 구현
5. 추가적으로 단일 User, 전체 User 반환 API 추가 구현
6. 정적 리소스 반환 코드를 작성했으나 매우 더러운 코드로 리팩토링 예정
7. User 회원가입, ServiceMapper 테스트 코드 추가
1. 현재 리팩토링한 클래스와 메서드들의 네이밍이 다소 애매하거나 이해하기 힘든 부분
8. String 으로 작성되어 있는 부분 enum 으로 변경
9. dispatcher 에 해당하는 부분 리팩토링
10. response 관련 부분 OOP 로 변경
11. 테스트 코드에 적합한 구조인지...
12. 어느 부분까지 테스트를 해야할지
13. ServiceMapper로 url 에 따른 Service 를 찾아서 리턴하는 로직 중간에 Controller 를 둬서 response 를 따로 치는게 좋을지?
1. 현재 구조가 WAS 에 적합한 것인지 계속해서 고민해나갈 예정
2. Service 관련 부분에 팩토리 메서드 패턴을 적용했는데 이 부분이 과연 확장성이 높은건지 재검증 예정

[99winnmin] step-2 GET으로 회원가입

---

.idea/codeStyles/codeStyleConfig.xml
src/main/java/db/Database.java
src/main/java/dto/user/request/UserCreateRequestDto.java
src/main/java/handler/DynamicRequestHandler.java
src/main/java/handler/RequestHandler.java
src/main/java/handler/ResponseHandler.java
src/main/java/handler/StaticResourceHandler.java
src/main/java/http/request/HttpMethod.java
src/main/java/http/request/HttpRequest.java
src/main/java/http/request/HttpRequestBody.java
src/main/java/http/request/HttpRequestHeader.java
src/main/java/http/request/HttpRequestStartLine.java
src/main/java/http/request/StaticResourceExtension.java
src/main/java/http/response/ContentType.java
src/main/java/http/response/HttpResponse.java
src/main/java/http/response/HttpResponseHeader.java
src/main/java/http/response/HttpResponseStartLine.java
src/main/java/http/response/HttpStatusCode.java
src/main/java/logger/CustomLogger.java
src/main/java/model/User.java
src/main/java/service/Service.java
src/main/java/service/ServiceMapper.java
src/main/java/service/user/OneUserSearchService.java
src/main/java/service/user/TotalUserSearchService.java
src/main/java/service/user/UserCreateService.java
src/main/java/service/user/UserServiceFactory.java
src/main/java/webserver/HttpProcessor.java
src/main/java/webserver/WebServer.java

1. HTTP Response 객체화
2. HTTP Method 및 정적 리소스 확장자 부분 열거형 객체화
1. 팩토리 메서드 패턴으로 구현되어 있는 ServiceFactory 구조 개선
전반적인 구조에 대해서 다시 체크하면서 Spring Servlet 동작 구조에 대해서 학습하고 적용해볼 예정이다. 추가적으로 Servlet 앞단에서 돌아가는 톰캣과 connector 관련한 내용도 체크해보려고 한다. WAS 에 대해서 좀 더 심층적인 학습을 진행해보려고 한다.

[99winnmin] step-2 코드 리뷰 반영 및 step-3 다양한 컨텐츠 타입 지원

---

src/main/java/controller/UserController.java
src/main/java/http/HttpContentType.java
src/main/java/http/HttpStatus.java
src/main/java/http/Request.java
src/main/java/http/Response.java
src/main/java/model/User.java
src/main/java/service/UserService.java
src/main/java/webserver/FrontController.java
src/main/java/webserver/ModelAndView.java
src/main/java/webserver/MyView.java
src/main/java/webserver/ViewResolver.java
src/main/java/webserver/dispatcher/SimpleRequestDispatcher.java

1. feed back 반영
1. logger 생성자에 class 명을 해당 class로 고쳐서 어느 클래스에서 출력된 에러인지 알 수 있게 하였습니다.
2. 사용하지 않는 library를 제거하였습니다.
2. 개선사항
1. viewResolver에서 absolut path를 return 하게 하여 viewResolver의 역할에 맞는 책임을 부여하였습니다.
2. 클린코드 작성법을 공부하고 메서드의 길이가 10줄이 넘는 메서드를 분리하였습니다.
3. 모든 클래스가 공유하는 클래스를 static으로 선언하여 메모리 누수를 방지하였습니다.

[jomulagy] step-2 & step-3 피드백 반영 및 refactoring

---

src/main/java/Controller/User/UserController.java
src/main/java/DTO/Request.java
src/main/java/DTO/Response.java
src/main/java/HandlerMapping/HandlerMapping.java
src/main/java/db/Database.java
src/main/java/model/User.java
src/main/java/webserver/RequestHandler.java
src/main/resources/templates/user/signup_failed.html
src/test/java/ControllerTest.java

1. URL parsing refactoring
2. test code를 작성하였다. db가 저장을 잘 하는지 여부를 확인.
3. signup을 fail했을 때 보내는 form을 변경.
url을 user 저장하게 만드는 controller에 전달하면 db 저장이 안된다.
분명히 static한 db임에도 불구하고 쓰레드간에 공유가 안된다는 사실이 이해가 안간다. 그래서 service layer?? 에서 test를 실행해 보았다.

[zensen6] step-3 다양한 컨텐츠 타입 지원

---

src/main/java/controller/FrontController.java
src/main/java/controller/StaticResourceController.java
src/main/java/controller/View.java
src/main/java/controller/adapter/StaticResourceHandlerAdapter.java
src/main/java/controller/user/UserCreateController.java
src/main/java/controller/user/UserFormController.java
src/main/java/controller/user/UserLoginController.java
src/main/java/webserver/RequestHandler.java
src/test/java/user/UserServiceTest.java

> - FrontController에서 Resource Requset에 대한 처리를 위함
> - Request의 요청 uri를 받아서 resource인지 체크 후 해당 컨트롤러가 처리하도록 구현
> -  Request를 처리 후 페이지 및 reource를 렌더링 해주기 위한 작업이 반복되기 때문
> - 여러 클래스에서 Uri를 다루는데 반복되는 내용이 존재하여 UriParser의 유틸 클래스를 만들어 관리할 예정
> - 공백이 들어가도 회원가입이 진행된다. 우선은 후순위로 구현 예정
> - 단위 테스트까지만 진행하게 된다면 현재 User 관련 로직인 회원가입까지만 진행하면 되는 것일까??

[lsh2613] Step-3 다양한 컨텐츠 타입 지원

---

src/main/java/controller/FrontController.java
src/main/java/controller/UserController.java
src/main/java/dto/ResourceDto.java
src/main/java/exception/ExceptionHandler.java
src/main/java/exception/SourceException.java
src/main/java/model/CommonResponse.java
src/main/java/model/QueryParam.java
src/main/java/model/QueryParams.java
src/main/java/model/RequestHeader.java
src/main/java/model/User.java
src/main/java/service/UserService.java
src/main/java/util/ErrorCode.java
src/main/java/util/HttpStatus.java
src/main/java/util/ResourceHandler.java
src/main/java/util/ResponseBuilder.java
src/main/java/webserver/PathHandler.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/RequestHeader.java
src/main/java/webserver/WebServer.java

**Controller를 매핑할 수 있는 FrontController를 구현하였습니다.**   
특정 URL의 요청시 해당 URL을 처리 가능한 Controller를 매핑하여 가져올 수 있는 FrontController를 구현하여 
처리 가능한 컨트롤러를 불러옵니다.    
처리가능한 Controller를 불러와서 헤더에 파싱된 메소드와 요청경로 정보를 활용하여 파라미터 파싱을 시도하여 QueryParams객체에 저장하게 됩니다. 전달된 파라미터에 따라서 컨트롤러에서 처리 가능한 메소드를 호출하여 각 요청에 맞는 Service로직을 수행하게 됩니다.
**ResourceHandler**
비즈니스 로직을 처리 후에 보여주고싶은 View를 선택할 수 있도록 합니다.    
보여주고 싶은 동적파일이 `./templates`경로에 있다면 resolveResource에서 경로의 html 또는 `./static` 경로의 정적파일 (css, js...)을 가져와 이를    
byte정보로 변환시켜 Response객체에 담을 수 있도록 합니다.      
이때 Redirect를 원한다면 해당 상태코드인 302를 넣게되면 해당 페이지로 리다이렉트를 보낼 수 있도록 합니다.
* 헤더를 요청시 java Reflection을 이용하여 헤더를 파싱을 하도록 하였습니다.    
헤더의 로그를 출력해보았을 때 너무 많은 정보를 출력하고 있었습니다. 따라서 유의미한 정보만을 담기 위하여 파싱해야했습니다.   
파싱을 위하여 if를 사용한 파싱은 유지성, 확장성을 고민하였을 때 좋지 않다고 생각하였습니다.    
따라서 헤더 객체를 따로 …

[Win-9] step-2 GET으로 회원가입

---

src/main/java/controller/UserControllerImpl.java
src/main/java/dto/HttpResponseDto.java
src/main/java/dto/UserSignUpDto.java
src/main/java/factory/HttpResponseFactoryImpl.java
src/main/java/handler/DynamicResponseHandlerImpl.java
src/main/java/handler/StaticResponseHandlerImpl.java
src/main/java/model/http/ContentType.java
src/main/java/model/http/Header.java
src/main/java/model/http/response/ResponseHeaders.java
src/main/java/model/http/response/StatusLine.java
src/main/java/service/HttpResponseSendServiceImpl.java
src/main/java/service/UserServiceImpl.java
src/main/java/util/FileDetector.java
src/main/java/util/HttpRequestParser.java
src/main/java/webserver/RequestHandler.java
src/test/java/webApplicationServer/controller/FakeHttpRequest.java
src/test/java/webApplicationServer/controller/FakeHttpResponseDto.java
src/test/java/webApplicationServer/controller/FakeUserService.java
src/test/java/webApplicationServer/controller/UserControllerImplTest.java
src/test/java/webApplicationServer/service/UserServiceImplTest.java

1. URL을 바탕으로 파일의 확장자를 Parsing하는 기능 추가.
2. ContentType Enum클래스에 화면구성에 필요한 추가적인 MIME타입들을 추가
3. 기존의 Mockito를 사용하던 테스트 코드를 Mock객체를 별도로 만들어 테스트
4. 추가적인 헤더를 실제 필드에서 HashMap으로 변경하여 nullPointException을 피하고 유동적이게 제작
1. Mockito 구현 실패
- 처음에는 Mockito를 제네릭과 Dynamic Proxy를 활용하여 구현해보려 하였지만 동적 타켓을 등록하는 곳에 반드시 인터페이스를 넣어야한다는 점에서 불필요하게 모킹에 필요한 모든 객체에 인터페이스가 필요해지는 단점과 구현난이도의 오버헤드가 커지는 것 같아 Mockito를 구현하는 대신  클래스들을 extends, Implement를 받는 가짜 구현객체를 만들어 테스트에 사용하였다.
- 이러한 과정을 거치며 이번 Mockito구현에는 사용하지 못하였지만 Dynamic Proxy를 조금 더 공부해 본다면 이번 WAS 프로젝트에 도입될 수 있는 부분이 하나정도는 생기지 않을까 라는 생각을 하게 되었고 바이트코드를 조작하는 CGLIB 라이브러리를 만약 사용할 수 있게된다면 Mockito를 보다 쉽게 모방할 수 있지않을까 생각이 들었다.

[dlwnsgus07] Step-3 다양한 컨텐츠 타입 지원

---

src/main/java/utils/UserFormDataParser.java
src/main/java/webserver/http/Mime.java
src/main/java/webserver/http/Request.java
src/main/java/webserver/http/RequestHandler.java
src/main/java/webserver/http/Response.java
src/main/java/webserver/http/ResponseHandler.java
src/main/resources/static/css/styles.css
src/test/java/webserver/http/RequestTest.java

1. MIME타입 ENUM형에 추가 및 Header에서 분리하여 ContentType 변경 로직 추가
2. Step2 피드백 적용
3. SonarLint적용후 피드백 적용
commit 할때 vim에서 개행문자를 넣으면 적용되지 않는다는 사실을 알게됨.

[sjmjys954646] Step-3 다양한 컨텐츠 타입 지원 

---

src/main/java/annotation/NotEmpty.java
src/main/java/annotation/RequestBody.java
src/main/java/constant/HttpStatus.java
src/main/java/constant/MimeType.java
src/main/java/controller/UserController.java
src/main/java/model/User.java
src/main/java/util/RequestMapper.java
src/main/java/util/RequestParser.java
src/main/java/util/ResourceLoader.java
src/main/java/webserver/HttpRequest.java
src/main/resources/logback.xml
src/main/resources/templates/user/form.html
src/test/java/controller/UserControllerTest.java

1. java.nio -> java.io 패키지 변경
- ResourceLoader에서 파일 관련해서 사용하던 함수들 변경
2. 확장자와 MIME타입을 매핑해주는 부분을 Map<String, String>에서 enum으로 변경
3. @RequestBody 어노테이션 추가 (RequestMapper :89 ~ :95에서 해당 어노테이션을 처리)
4. /user/createmethod를 POST로 변경 (그에 따른 테스트코드도 아주 약간의 수정)
5. logger에서 로그 찍을 때 무슨 파일의 몇 번째 줄에서 찍은 로그인지 추가
이번 과제에서 회원가입은 application/x-www-form-urlencoded 형식으로 하지만
사실 POST요청은 application/json 형식으로 오는 경우가 많아서,
Request Header의 Content-Type별로 파싱 로직을 다르게 처리하는 부분을 추가하고 싶은데
이번주 과제에 그런 기능을 추가해야 할 것 같은 요구사항은 나와있지 않으니 일단 패스했다.
만약 JSON으로 요청이 오는 경우가 추가된다면, 혹은 과제를 다 끝내고 나서도 시간이 남는다면... 해볼 생각
커밋은 기능 하나당 하나씩 올리라고 하셨는데 또 한번에 올려버렸다 으악

[insiderhj] step-4 POST로 회원 가입

---

src/main/java/Controller/User/UserController.java
src/main/java/DTO/HttpStatus.java
src/main/java/DTO/Response.java
src/main/java/Functions/FileBytes.java
src/main/java/HandlerMapping/HandlerMapping.java
src/main/java/webserver/RequestHandler.java
src/main/resources/templates/user/form.html

기존 body만 보내던 것을 Response로 통일
Response에는 HTTPStatus와 body등이 들어있고, HTTPStatus 가 302 상태인 경우에는 redirection url또한 포함되어있다.
이 Response를 doc.write형태로 함수 작성을 하였고 타 친구의 소스를 참고하였다.
그 외에도 nio를 io 로 대체하였다.
response의 구조에 대해 조금 더 자세히 알아봐야 할 것 같다.
만약 contents body는 A라는 html을 보내고, redirect url은 쌩판 관련없는 B url를 첨부한다면 어떻게 되는지 궁금하다.

[zensen6] POST로 회원 가입 

---

src/main/java/controller/View.java
src/main/java/webserver/RequestHandler.java
src/main/resources/templates/user/form.html

[lsh2613] Step-4 POST로 회원가입

---

src/main/java/annotation/PostMapping.java
src/main/java/controller/UserController.java
src/main/java/util/ControllerMapper.java
src/main/java/util/MethodMapper.java
src/main/java/util/ResourceLoader.java
src/main/java/util/URIParer.java
src/main/java/webserver/HttpRequest.java
src/main/java/webserver/HttpResponse.java
src/main/java/webserver/HttpStatus.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/RequestMappingHandler.java
src/main/resources/templates/user/form.html
src/test/java/UserControllerTest.java

어노테이션을 사용하지 않았을 때에는 GetController, PostController 와 같이 HTTP Method로 Controller를 구분했었다.
그러나 저번 주에 @GetMapping 어노테이션을, 오늘은 @PostMapping 어노테이션을 만들었기 때문에 Controller를 도메인 별로 다시 나누었다.
Request가 오면 해당 request의 method를 보고 어떤 어노테이션을 읽어야 할 지 결정하고, 해당 어노테이션이 붙은 메소드의 path와 request의 path가 일치하면 해당 메소드가 실행되는 방식으로 진행된다.
> http://localhost:8080/user/form.html 파일의 form 태그 method를 get에서 post로 수정한다.
> 나머지 회원가입 기능이 정상적으로 동작하도록 구현한다.
> 가입 후 페이지 이동을 위해 HTTP redirection 기능을 구현한다.
1번에서 언급한 @PostMapping을 통해 회원가입 메소드를 **POST**로 변경하였다.
기존 **GET** 방식을 사용할 때에는 URI를 파싱하는 방식이었는데, **POST**를 사용하니 Request Body를 읽고 파싱하는 방식으로 코드를 변경해야 했다.
Request Body는 Request Header 뒤에 한 줄 띄고 _{key}={value}&{key}={value}_ 의 형식으로 오는데, 이 친구를 `br.readLine()`으로 받으려 했다. Request Body는 뒤에 개행 문자가 없기 때문에 `br.readLine()`을 사용하면 안 됐다 !
Request Header 중 …

[h-sooah]  step-4 POST로 회원 가입

---

README.md
src/main/java/utils/HttpRequestParser.java
src/main/java/utils/HttpResponseSender.java
src/main/java/webserver/HttpRequest.java
src/main/java/webserver/RequestHandler.java
src/main/resources/templates/user/form.html
src/test/java/RequestParserTest.java

POST로 회원가입 구현
HttpRequestParser에서 헤더와 바디를 구분해서 추출하는 것

[seojeewon] step-4 POST로 회원가입

---

README.md
src/main/java/utils/RequestBodyParse/ParserFactory.java
src/main/java/utils/RequestBodyParse/RequestBodyParser.java
src/main/java/utils/RequestBodyParser.java
src/main/java/utils/UserFormDataParser.java
src/main/java/webserver/HttpConnectionHandler.java
src/main/java/webserver/WebServer.java
src/main/java/webserver/http/ContentType.java
src/main/java/webserver/http/HttpMethod.java
src/main/java/webserver/http/Request.java
src/main/java/webserver/http/RequestHandler.java
src/main/java/webserver/http/Response.java
src/main/java/webserver/http/ResponseHandler.java
src/main/resources/templates/user/form.html

1. parsing알고리즘이 body를 가져오지 못하는 문제 해결. Body 뒤에는 \n이 입력받지 못하여 EOF를 계속 기다렸던 것. ContentLength를 전달해주는데는 이유가 있었음.
2. 여러 content를 처리하기 위해 팩토리 패턴 학습및 사용
3. GET /api/user POST /api/user 등의 요청 처리를 위해서 기존 String url 처리를 Route객체로 처리
RequestHandler에서 route하는 부분 역시 팩토리 패턴으로 해야되는가? 아니면 다른 방법이 있을까? 아니면 현재 방식대로 요청이 추가 될때 마다 HashMap에 추가하는 형태로 해야하는가.

[sjmjys954646] step-4 POST로 회원 가입

---

src/main/java/controller/UserController.java
src/main/java/util/SessionManager.java
src/main/java/webserver/HttpRequest.java

* SessionManager를 통해 세션 관리
* 로그인 성공 시 세션을 등록하고 클라이언트에게 Set-Cookie 헤더를 통해 SID 반환

[insiderhj] step-5 쿠키를 이용한 로그인

---

src/main/java/controller/UserController.java
src/main/java/http/request/HttpRequest.java
src/main/java/utils/ControllerMapper.java
src/main/java/utils/FileReader.java
src/main/java/utils/Parser.java
src/main/java/webserver/RequestHandler.java
src/main/resources/templates/user/form.html

```html
<form name="question" method="post" action="/user/create">
... // 회원가입 폼 생략
</form>
```
```java
static {
CONTROLLER.put("POST /user/create", UserController::signup);
}
```
```java
// body부 받기
if (etcHeaders.containsKey("Content-Length")) {
// Content-Length의 길이가 페이로드의 길이
// 해당 길이만큼 남은 데이터 읽어오기
int len = Integer.parseInt(etcHeaders.get("Content-Length"));
char[] buffer = new char[len];
int bytesRead = br.read(buffer, 0, len);
line = new String(buffer, 0, bytesRead);
body = Parser.extractParams(line);
}
```
```java
public static byte[] readFile(File file) {
try {
// 파일을 읽어오기 위한 FileInputStream 생성
FileInputStream fis = new FileInputStream(file);
// 파일 내용을 저장할 ByteArrayOutputStream 생성
ByteArrayOutputStream bos = new ByteArrayOutputStream();
// 파일 내용을 읽어와서 ByteArrayOutputStream에 쓰기
// …
```

[ossu] step-4 POST로 회원 가입

---

src/main/java/config/HTTPRequest.java
src/main/java/config/HTTPResponse.java
src/main/java/config/ResponseCode.java
src/main/java/controller/PageController.java
src/main/java/controller/UserController.java
src/main/java/webserver/ControllerHandler.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/WebServer.java
src/main/resources/templates/user/form.html
src/test/java/webserver/RequestHandlerTest.java

1. html뿐만 아니라 static폴더에 있는 컨텐츠들을 로딩 할 수 있도록 수정.
2. Request 헤더에서 Accept를 참고하여 Content-Type을 작성.
Content-Type을 static에 있는 컨텐츠의 확장자와 MIME 타입을 참고해서 작성하는게 맞을지, 아니면 Accept를 참고해서 일단 보내는게 맞을지 고민을 했다.
고민사항에서: 전자가 맞다. 클라이언트가 리소스를 해석하거나 다룰 때 Content-Type을 참고 할 수가 있기 때문에 이 부분은 MIME Type을 확장자를 기준으로 제대로 해주는게 맞다.
==========================
1. 회원가입 요청이 GET이 아닌 POST일 때 데이터를 받고 저장할 수 있다.
2. Body에서 회원가입 정보를 파싱 한다.
4. 회원가입을 성공 했을 경우 리디렉션을 수행한다.
Step-4를 구현 중심으로 하다보니 코드가 난잡해지고 예외처리나 기능 분리가 제대로 이루어지지 않았다. 
어제부터 Step-5를 작업하고 있었는데 그런 부분이 많이 보여 전체적으로 수정중이다. 
세션에 대한 학습을 급하게 시작하는 바람에 현재 브랜치에서는 아래 요구사항이 반영되지 않았다.
이미 step5 브랜치가 많이 진행 되어서 다음 PR 때 같이 반영될 예정이다.
1. 예외처리 ( 회원가입에 실패 했을 경우)
2. nio -> io 수정
3. Request Body 처리

[eyeben] step-4 POST로 회원 가입

---

README.md
docs/step-1-README.md
docs/step-2-README.md
docs/step-4-README.md
src/main/java/annotation/Column.java
src/main/java/controller/Controller.java
src/main/java/controller/HomeController.java
src/main/java/controller/UserController.java
src/main/java/model/User.java
src/main/java/request/HttpRequest.java
src/main/java/response/HttpResponse.java
src/main/java/response/StatusLine.java
src/main/java/service/UserService.java
src/main/java/util/MimeType.java
src/main/java/util/Parser.java
src/main/java/util/Uri.java
src/main/java/webserver/DispatcherServlet.java
src/main/java/webserver/ViewResolver.java
src/main/resources/templates/user/form.html
src/test/java/controller/HomeControllerTest.java
src/test/java/controller/UserControllerTest.java
src/test/java/service/UserServiceTest.java
src/test/java/util/ParserTest.java

>1. form.html에서 method를 POST로 변경한다.
>2. 요청을 처리할 컨트롤러인 UserController를 찾는다.
>3. 해당 컨트롤러에서 jsonParser 메소드를 통해 요청 본문을 파싱하고 User 객체를 생성한다.
>4. 생성된 User 객체를 통해 UserService의 signUp 메소드를 호출하여 회원가입을 진행한다.
<br>
>1. 회원가입이 완료되면, HttpResponse 객체를 생서하고 Location 헤더에 redirect uri를 설정한다.
>2. 302 상태코드를 응답하게 되면, 브라우저는 Location 헤더에 설정된 uri로 재요청을 보낸다.
>    - 변경전: ViewResolver에서 redirect uri를 "/index.html"로 하드코딩하여 작성
>    - 변경후: Controller에서 요청에 따라 redirect uri를 다르게 설정하여 HttpReponse 객체에 Location 헤더를 설정
>1. File.readAllBytes() 메소드 -> FileInputStream 사용
>2. Path 객체를 이용한 파일 읽기 -> String 객체를 이용한 파일 읽기
1. 테스트를 위해서 User 객체를 생성했지만, User 클래스의 생성자 및 필드값이 private이기 때문에 외부에서 객체를 생성할 수 없었다.
reflection을 사용해서 접근 제어자를 무시하고 User 객체를 생성할 수 있었지만, 이러한 경우에 유연성이 지나치게 높아지고 캡슐화의 본래 목적을 해치게 될 수 있다는 생각을 하게 되었다.
미션에서 외부 라이브러리 사용을 금지하고 …

[taegon98] step-4 POST로 회원 가입

---

README.md
src/main/java/db/Database.java
src/main/java/dto/Login.java
src/main/java/model/Session.java
src/main/java/service/UserService.java
src/main/java/utils/HttpRequestParser.java
src/main/java/utils/HttpResponseSender.java
src/main/java/webserver/HttpRequest.java
src/main/java/webserver/RequestHandler.java

- HttpResponseSender에서 로그인 성공 후 /index.html로 리다이렉션할 때 `Set-Cookie` 헤더를 통해 세션(id, expireTime) 전달 
- userService의 login 메서드에서 java.util 패키지의 UUID를 이용해 무작위 숫자 배정
POST와 GET 메서드, Path를 RequestHandler에서 분기해서 3중 if-else문이 되었다. 리팩토링을 생각해보아야 할 것 같다.

[seojeewon] step-5 쿠키를 이용한 로그인

---

src/main/java/Controller/User/UserController.java
src/main/java/DTO/Request.java
src/main/java/DTO/Response.java
src/main/java/Functions/FileBytes.java
src/main/java/HandlerMapping/HandlerMapping.java
src/main/java/webserver/RequestHandler.java
src/test/java/ControllerTest.java

Cookie 및 Session 구현
response에 sid 넣어 보내면 다음부터 request는 동일한 sid를 서버로 보낸다.
아직 깔끔한 구성까진 고려하지 않고
request로부터 cookie sid 값을 가지고서 로그인을 구현하는 정도까진 왔다.
다른분들의 로직을 들어보고 비교해봐야할 것 같다.

[zensen6] Step-5 쿠키를 이용한 로그인 

---

src/main/java/controller/Controller.java
src/main/java/controller/FrontController.java
src/main/java/controller/UserController.java
src/main/java/http/HttpRequest.java
src/main/java/http/HttpResponse.java
src/main/java/http/HttpResponseHandler.java
src/main/java/http/HttpStatus.java
src/main/java/http/MimeType.java
src/main/java/webserver/HttpRequest.java
src/main/java/webserver/HttpResponse.java
src/main/java/webserver/HttpStatus.java
src/main/java/webserver/RequestHandler.java
src/main/resources/templates/user/form.html

기존의 GET 요청은 request 파라미터를 읽어오지만, **POST 요청은 body**를 읽어와야 한다.
이를 위해 http header를 읽어오던 방식대로 readLine()을 사용했으나 회원가입 버튼을 두번 눌러야 동작했다.
이유를 찾아보니 readLine()은 개행문자가 들어올 때까지 입력받는데, **http body의 끝에는 개행문자가 없어서** 입력을 못 받는 것이었다.
**read()로 변경**하여 입력받으니 잘 동작하였다.
그동안 구현에만 급급하여 RequestHandler에 거의 모든 코드를 작성하였다.
FrontController, HttpResponseHandler를 만들어 분리했다.
**- FrontController**
어떤 controller를 실행할지 결정 후 실행
**- HttpResponseHandler**
http 상태코드를 세팅하고 상태코드마다 필요한 헤더 세팅
이후 RequestHandler
```java
HttpRequest request = new HttpRequest(in); //http request 정보 가져오기
request.print(); //http request 정보 출력
HttpResponse response = new HttpResponse(dos);
frontController.process(request, response);
responseHandler.setHttpResponse(response);
response.sendResponse();
```
기존에 301 Moved Permanently로 되어있었는데, 찾아보니 **301은 영구적인 …

[eekrwl] step-4 웹 서버 4단계 - POST로 회원 가입

---

src/main/java/constant/ErrorCode.java
src/main/java/constant/FileContentType.java
src/main/java/constant/FilePath.java
src/main/java/constant/HttpStatus.java
src/main/java/controller/UserController.java
src/main/java/dto/RequestDto.java
src/main/java/dto/ResponseDto.java
src/main/java/service/UserService.java
src/main/java/session/Session.java
src/main/java/util/FileManager.java
src/main/java/util/MethodMapper.java
src/main/java/util/RequestParser.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/ResponseHandler.java
src/test/java/service/UserServiceTest.java

* 랜덤한 세션 아이디를 생성하는 메소드
* 세션을 보관할 시간을 설정, 세션 만료 기능
* POST 로 /user/login 경로로 들어온 요청 처리 (로그인한 유저가 또 로그인한 경우 고려)
* 회원가입한 유저인지, 틀린 비밀번호를 입력했는지 확인하고 예외 처리
* 로그인에 성공하면 응답 헤더의Set-Cookie에 생성한  senssionId를 보내주기
* ResponseDto 클래스 생성
* ResponseHandler의 send200, sendError 등의 메소드를 send()로 통일
기존의 방식은 http상태 코드별로 응답을 전송하는 메소드를 만들어 사용했었다.
body가 있는 경우 `sendBody()`, 
리다이렉트 해야하는 경우는 `sendRedirect()`, 
에러가 발생한 경우 `sendError()`를 호출해 응답을 보냈는데,
나머지는 다 똑같고 헤더만 하나 추가되도, 해당 응답을 전송하기 위해 ResponseHandler에 새로운 메소드를 작성해야 했다.
이런 식으로 응답의 종류별로 메소드를 하나씩 생성하는 것은 확장성이 좋지 않고 유지보수가 굉장히 힘든 코드임을 느꼈고,
이를 개선하기 위해 ResponseDto를 생성해 좀 더 유연하게 응답을 생성하고,
ResponseHandler에는 ResponseDto를 매개변수로 받아 응답을 전송하는 send() 메소드 하나만 두어,
생성한 응답을 공통적으로 전송할 수 있게 하였다.
```java
public static void send(DataOutputStream dos, ResponseDto responseDto) {
try {
// …
```

[kelly1422] step-5 쿠키를 이용한 로그인

---

src/main/java/config/ExceptionHandler.java
src/main/java/config/HTTPRequest.java
src/main/java/config/HTTPResponse.java
src/main/java/config/Session.java
src/main/java/controller/PageController.java
src/main/java/controller/UserController.java
src/main/java/webserver/ControllerHandler.java
src/main/java/webserver/RequestHandler.java
src/test/java/webserver/RequestHandlerTest.java

1. 가입한 회원정보로 로그인 할 수 있다.
2. 로그인 메뉴를 클릭하면 로그인 화면으로 이동할 수 있다.
3. 로그인이 성공하면 index.html로 이동한다.
4. 로그인이 실패하면 /user/login_failed.html로 이동한다.
5. 예외처리 ( 회원가입에 실패 했을 경우)
6. nio -> io 수정
구조를 역할별로 최대한 분리하는게 맞다고 생각하는데 어느부분을 해야할지 잘 모르겠다.  반복적인 구조가 나오면 그때부터 수정을 하는 방식으로 진행 했었는데  이 방식이 좋은 방법인지는 잘 모르겠다.
나중에 전체적으로 구조를 변경하는 순간이 올 까봐 무섭다. 지금은 구조를 연구하는것보다 자바관련해서 배운 내용들을 다 써보는것을 목표로 잡을 생각이다.

[eyeben] step-5 쿠키를 이용한 로그인

---

src/main/java/controller/UserControllerImpl.java
src/main/java/dto/HttpResponseDto.java
src/main/java/dto/UserLoginDto.java
src/main/java/dto/UserSignUpDto.java
src/main/java/exception/InvalidLogin.java
src/main/java/factory/HttpRequestFactoryImpl.java
src/main/java/factory/HttpResponseFactoryImpl.java
src/main/java/handler/DynamicResponseHandlerImpl.java
src/main/java/handler/StaticResponseHandlerImpl.java
src/main/java/model/http/Body.java
src/main/java/model/http/Cookie.java
src/main/java/service/HttpResponseSendServiceImpl.java
src/main/java/service/UserService.java
src/main/java/service/UserServiceImpl.java
src/main/java/session/Session.java
src/main/java/util/FileDetector.java
src/main/java/webserver/RequestHandler.java
src/test/java/webApplicationServer/controller/FakeHttpRequest.java
src/test/java/webApplicationServer/controller/FakeUserService.java
src/test/java/webApplicationServer/controller/UserControllerImplTest.java

1. ConcurentHashMap에 대하여 학습 후 이를 활용하여 Thread Safe한 메모리 Session을 생성 -> 이 과정중에 Read와 Put사이에 생기는 잘못된 상태를 막기위해  synchronize를 메서드에 활용하여 구현
2. Response에 쿠키를 담는 기능 구현, Session에서 user를 구분하는 기준을 UUID로 두고 UUID와 Path를 쿠키에 담아서 개발
3. 브라우저 개발자 도구를 통해 쿠키가 정상적으로 담기는 지 확인 
4. 로그인이 성공하면 index.html로 이동하는 기능
5. 로그인이 실패할 시 /user/login_failed.html 로 Redirect시킨다.
6. 기존에 바이너리파일 손실을 막기위해 byte배열을 그대로 body에 저장하던 것을 Base64 encoder, decoder를 사용하여 String 형태로 저장하는 기능 추가.
1. 쿠키와 세션을 사용하는 이유
- HTTP의 비연결성과 비상태성을 보안하기 위해
2. 인가와 인증
- 인가와 인증의 차이점
3. Scale out시 나타날 수 있는 Session의 정합성 문제 해결점
-  Sticky Session
-  Session 클러스터링
-  Session Storage 분리 
각각의 장단점
- 다양한 코드 피드백을 받았는데 Step-6까지 기능구현을 하고 난 뒤 한번에 적용해볼 생각이다.
- 특히 변수명 depth가 잘못된거같다는 부분이 있었는데 이부분을 어떻게 고치고 다른 개발자들이 보았을때 납득 할 수 있을지 고민해봐야겠다.
- 컨트롤러에서 IF문을 통해서 url을 구분하고 핸들링하고 있는데 …

[dlwnsgus07] Step-5 쿠키를 통한 로그인

---

src/main/java/http/Request.java

- 문제 상황
- 1024Byte보다 큰 body 가 요청이 들어올 경우 안전하지 않은 코드가 될 수 있다.
- 해결 방안
- content Length 헤더를 읽고 content Length 만큼 body를 읽는다.
```
byte[] buffer = new byte[contentLength];
```

[jomulagy] step-4 피드백 반영

---

src/main/java/db/Database.java

디비 조금 업데이트

---

README.md
docs/step-6-README.md
src/main/java/annotation/GetMapping.java
src/main/java/annotation/PostMapping.java
src/main/java/controller/HomeController.java
src/main/java/controller/UserController.java
src/main/java/db/Database.java
src/main/java/db/Session.java
src/main/java/request/http/HttpRequest.java
src/main/java/response/http/HttpResponse.java
src/main/java/service/UserService.java
src/main/java/util/AuthFilter.java
src/main/java/webserver/DispatcherServlet.java
src/main/java/webserver/HttpResponseHandler.java
src/main/resources/templates/index.html
src/main/resources/templates/user/form.html
src/main/resources/templates/user/form_failed.html
src/main/resources/templates/user/list.html
src/main/resources/templates/user/login.html
src/main/resources/templates/user/login_failed.html
src/test/java/controller/UserControllerTest.java
src/test/java/service/UserServiceTest.java
src/test/java/util/AuthFilterTest.java

>1. 브라우저의 쿠키에 저장된 세션 정보를 통해 사용자가 로그인 상태인지 확인한다.
>   - sid, user-name 쿠키가 존재하는지 확인한다.
>   - 쿠키가 존재한다면, user-name 쿠키의 값을 읽고 navbar에 사용자 이름, Posts, 회원목록, 로그아웃 버튼을 표시한다.
>   - 쿠키가 존재하지 않는다면, navbar에 Posts, 로그인, 회원가입 버튼을 표시한다.
>1. 브라우저의 쿠키에 저장된 세션 정보를 통해 사용자가 로그인 상태인지 확인한다.
>  - 로그인 상태가 아닐 경우, 로그인 페이지(/user/login.html)로 이동한다.
>  - 로그인 상태일 경우, 사용자 목록을 출력한다.
>2. 사용자 목록을 출력하기 위해, StringBuilder의 replace() 메서드를 사용하여 매 요청마다 동적인 HTML을 응답하도록 구현하였다.
>   ```java
>    StringBuilder replacedBuffer = new StringBuilder(fileContent);
>    replacedBuffer.replace(replacedBuffer.indexOf("{{userList}}"),
>    replacedBuffer.indexOf("{{userList}}") + "{{userList}}".length(),
>    builder.toString());
1. 중복 코드: 가독성을 높이기 위해 의미별로 메서드를 분리하면서 코드를 작성했던 것 같다.
중복되는 코드가 있다는 피드백을 받고 전체 코드를 읽어가며 중복되는 코드를 하나의 메서드로 합쳤지만, 메서드의 …
```

[taegon98] step-6 동적인 HTML

---

src/main/java/controller/UserController.java
src/main/java/service/UserService.java
src/main/java/utils/HtmlBuilder.java
src/main/java/utils/ResourceReader.java
src/main/java/utils/SessionManager.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/http/request/HttpRequest.java
src/main/java/webserver/http/request/HttpRequestParser.java
src/main/java/webserver/routing/DynamicRoutingManager.java
src/main/java/webserver/routing/StaticRoutingManager.java
src/main/resources/templates/index.html
src/main/resources/templates/user/list.html

**1. 동적 사용자 목록 구현**
> 사용자가 로그인 상태일 경우 http://localhost:8080/user/list 에서 사용자 목록을 출력한다.
http://localhost:8080/user/list  페이지 접근시 로그인하지 않은 상태일 경우 로그인 페이지(login.html)로 이동한다.
- list.html의 사용자 목록을 동적 HTML로 구현하여 기존의 정적 템플릿에 삽입하는 방식으로 변경
- 동적으로 동작해야 하는 부분을 주석으로 표시하고 동적 HTML 부분을 이 주석 위치에 삽입하여 업데이트
- 특수 문자 처리를 개선하여 회원 가입 시 이메일 등의 특수 문자가 퍼센트 인코딩되어 저장되는 문제 해결
- 로그인하지 않은 사용자가 list.html에 접근 시 리다이렉션 처리
**2. 로그인 상태 확인 및 UI 변경**
> 사용자가 로그인 상태일 경우 /index.html에서 사용자 이름을 표시해 준다.
사용자가 로그인 상태가 아닐 경우 /index.html에서 [로그인] 버튼을 표시해 준다.
- UserController에 사용자의 로그인 여부를 확인하는 로직 추가
- 로그인 상태일 경우 /index.html에서 사용자 이름, 로그아웃, 개인정보수정 버튼 표시
- 로그인 상태가 아닐 경우 /index.html에서 로그인, 회원가입 버튼 표시
**1. 네비게이션 바 그리기**
HTML의 네비게이션 바를 전체적으로 그리기 vs 필요 없는 HTML 태그들을 주석 처리하기
초기에는 동적HTML을 정적 템플릿에 삽입하는 과정에서 태그의 앞뒤로 특정 주석을 추가한 후, 필요에 따라 특정 태그들을 …

[isExample] step-6 동적인 HTML

---

src/main/java/content/FileContent.java
src/main/java/controller/FrontController.java
src/main/java/controller/UserController.java
src/main/java/db/Database.java
src/main/java/dto/ResourceDto.java
src/main/java/model/CommonResponse.java
src/main/java/model/Model.java
src/main/java/service/UserService.java
src/main/java/util/ErrorCode.java
src/main/java/util/Param.java
src/main/java/util/ParseParams.java
src/main/java/util/ResourceHandler.java
src/main/java/util/ResponseBuilder.java
src/main/java/util/Session.java
src/main/java/webserver/PathHandler.java
src/main/java/webserver/RequestHandler.java
src/main/java/webserver/RequestHeader.java
src/main/resources/templates/index.html
src/main/resources/templates/user/form.html
src/main/resources/templates/user/list.html
src/main/resources/templates/user/login.html
src/test/java/service/UserServiceTest.java

**PR 보낼때 위 내용은 모두 삭제하고 보내세요.**
인덱스 뷰에서 사용자 정보를 볼 수 있도록 하였습니다. 로그인이 안되어 있을때는 Post, 로그인, 회원가입을 수행할 수 있고,    
로그인 후에는 Post, 회원정보수정, 사용자 정보를 볼 수 있습니다. 이는 인덱스 뿐만 아니라 모든 화면에서 수정된 바를 볼 수 있습니다.    
ResourceHandler에서 html리소스를 받는 순간 미리 삽입된 태그와 준비된 HTMl태그를 치환합니다.
미리 삽입된 태그를 치환시켜 사용자 정보를 담은 Model에서 정보를 가져와 치환을 수행합니다.
/user/list에서는 현재 데이터베이스에 있는 사용자를 모두 보여줄 수 있습니다.   
모든 사용자 정보를 Model에 List형태로 담아서 치환시 HTML태그 형식에 맞게 파싱과 치환을 수행합니다.
/user/list에 접근시에는 로그인을 해야하는 사전 준비가 되어야 합니다.   
따라서 로그인의 session값의 유무에 따라서 값이 존재하지 않는다면 Login화면으로 redirection을 수행하게 됩니다.   
로그인 시에는 모든 사용자의 정보들을 동적으로 볼 수 있도록 하였습니다.
---
* 고민사항
> 구현한 로직들이 복잡해지면서 구조적인 리펙토링이 필요하다고 느껴집니다.    
OOP의 원칙에 따라 역할들을 분리하여 확장성있고 유지보수가 가능하도록 재 설계가 필요하다고 생각합니다.   
코드의 품질을 높이는 것과 기간 내의 구현중 어느 것이 더 가치있는 것인지 다시끔 고민해보도록 하는 과정을 겪고 있습니다.   
* 고민사항
> 현재 쿠키 정보를 이용하기 …

[Win-9] step-6 동적인 HTML

---

README.md
src/main/java/controller/FirstController.java
src/main/java/controller/LastController.java
src/main/java/controller/MainController.java
src/main/java/controller/UserController.java
src/main/java/db/SessionStorage.java
src/main/java/model/Request.java
src/main/java/model/Response.java
src/main/java/model/Session.java
src/main/java/model/StatusCode.java
src/main/java/utils/Util.java
src/main/resources/templates/index.html
src/main/resources/templates/qna/form.html
src/main/resources/templates/qna/show.html
src/main/resources/templates/user/form.html
src/main/resources/templates/user/list.html
src/main/resources/templates/user/login.html
src/main/resources/templates/user/login_failed.html
src/main/resources/templates/user/profile.html

StringBuilder클래스의 replace함수를 사용해서 동적인 페이지 구현
navbar에 {{login}} 부분은 로그인이 확인되면 userId, 로그아웃, 개인정보수정을 출력하고 로그아웃 시 로그인, 회원가입 출력
/user/list.html에 {{list}} 부분은 로그인이 확인되면 user들의 정보를 출력
MainController의 route함수 실행시 세션스토리지의 만료된 세션들을 삭제 처리, 현재 쿠키에 담긴 세션을 검증해 로그인 여부 확인
StatusCode Enum 클래스를 활용해 Response 객체를 좀 더 체계적으로 관리
로그아웃시 브라우저에 저장된 sessionId 쿠키를 삭제 처리하고 index.html로 리다이렉션 처리
동적인 페이지를 구현하기 위해 현재 html의 일부분을 하드코딩해 replace하고 있는데
이런 방식으로는 확장가능성이 낮다고 생각해 좀 더 좋은 방법을 찾아봐야 할 것 같다.

[binaryrain97] step-6 동적인 HTML

---

README.md
build.gradle
docs/step-7-README.md
gradle/wrapper/gradle-wrapper.properties
src/main/java/controller/BoardController.java
src/main/java/controller/HomeController.java
src/main/java/controller/UserController.java
src/main/java/db/Database.java
src/main/java/model/Board.java
src/main/java/model/User.java
src/main/java/request/http/HttpRequest.java
src/main/java/request/http/RequestHeaders.java
src/main/java/response/http/HttpResponse.java
src/main/java/service/BoardService.java
src/main/java/service/UserService.java
src/main/java/util/Parser.java
src/main/java/webserver/DispatcherServlet.java
src/main/resources/templates/board/show.html
src/main/resources/templates/board/write.html
src/main/resources/templates/index.html
src/main/resources/templates/user/list.html
src/test/java/controller/HomeControllerTest.java
src/test/java/controller/UserControllerTest.java
src/test/java/service/UserServiceTest.java
src/test/java/util/AuthFilterTest.java

- ### 글쓰기 기능 구현
- 요청 헤더의 Cookie에 담긴 sid의 유효성을 검사하여 로그인 여부를 판단했다.
- replace() 메서드를 사용하여 index.html의 특정 위치에 작성한 글의 제목을 삽입했다.
<br>
- ### 글쓰기에 파일 첨부 기능 추가
- 요청 body에 파일이 포함되어 전송되도록 구현했다.
- Multipart/form-data 형식으로 전송될 경우, body의 형태가 달라지기 때문에, 파일이 포함되어 있는지 여부를 확인하였다.
- 파일이 포함되어 있을 경우, 해당 파일의 데이터 값을 byte[]로 저장 후 /static 경로에 파일을 생성하였다.
- 파일이 포함되어 있지 않을 경우, body의 데이터 값을 파싱하여 String 형태로 저장하였다.
<br>
- ### 세부 글 표시 기능 구현
- 세부 내용 페이지에서는 글의 제목, 내용, 작성자, 작성일, 첨부파일을 확인할 수 있다.
- 게시글에 이미지가 첨부되어 있다면, index.html에서 게시글 제목 왼쪽에 해당 이미지를 작게 표시한다.
- ### 404 및 기타 에러 처리 페이지 구현
- 서버에서 존재하지 않는 URL에 대한 요청을 받으면, 404 페이지로 응답하도록 구현했다.
- ### DB 연동
- 정적 초기화 블록을 사용하여 H2 데이터베이스를 연결하고, 필요한 테이블 생성 및 mock 데이터를 삽입했다.
- JDBC를 사용하여 H2 데이터베이스에 접근하고, 회원정보와 게시글을 저장하도록 구현했다.
- ### POST 파일 업로드 처리
- 파일 업로드를 위한 form 태그를 작성하고, enctype 속성을 …

[taegon98] step-7 게시판 기능 완성
